'use strict';
/**
 * scripts/setup.js — Interactive first-time setup wizard
 * Run: node scripts/setup.js
 *
 * This script:
 *  1. Checks Node.js version
 *  2. Installs dependencies
 *  3. Creates your .env file interactively
 *  4. Validates each API key
 *  5. Runs a quick pipeline smoke-test
 */

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');
const { execSync } = require('child_process');

const ROOT    = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const ENV_EXAMPLE = path.join(ROOT, '.env.example');

// ── Colors ────────────────────────────────────────────────────────────────────
const C = {
  reset: '\x1b[0m',
  bold:  '\x1b[1m',
  green: '\x1b[32m',
  yellow:'\x1b[33m',
  red:   '\x1b[31m',
  cyan:  '\x1b[36m',
  blue:  '\x1b[34m',
};

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

function print(msg) { process.stdout.write(msg + '\n'); }
function ok(msg)    { print(`${C.green}✅ ${msg}${C.reset}`); }
function warn(msg)  { print(`${C.yellow}⚠️  ${msg}${C.reset}`); }
function err(msg)   { print(`${C.red}❌ ${msg}${C.reset}`); }
function info(msg)  { print(`${C.cyan}ℹ️  ${msg}${C.reset}`); }
function header(msg){ print(`\n${C.bold}${C.blue}${'═'.repeat(56)}\n  ${msg}\n${'═'.repeat(56)}${C.reset}\n`); }

// ── Entry point ───────────────────────────────────────────────────────────────
async function main() {
  header('YouTube AI Agent — Setup Wizard');

  // 1. Node version check
  const [major] = process.version.replace('v','').split('.').map(Number);
  if (major < 18) {
    err(`Node.js 18+ required. You have ${process.version}`);
    err('Download from: https://nodejs.org');
    process.exit(1);
  }
  ok(`Node.js ${process.version}`);

  // 2. Install dependencies
  print('\n📦 Installing dependencies...');
  try {
    execSync('npm install', { cwd: ROOT, stdio: 'inherit' });
    ok('Dependencies installed');
  } catch(e) {
    err('npm install failed. Check your internet connection.');
    process.exit(1);
  }

  // 3. Check if .env already exists
  if (fs.existsSync(ENV_PATH)) {
    const overwrite = await ask(`\n${C.yellow}.env file already exists. Overwrite? (y/N): ${C.reset}`);
    if (overwrite.trim().toLowerCase() !== 'y') {
      info('Keeping existing .env. Skipping to validation...');
      await validate();
      rl.close();
      return;
    }
  }

  header('Step 1 of 5 — Channel Identity');
  info('This name goes on your thumbnails and in script CTAs.');
  const channelName = (await ask(`Your channel name (e.g. NGL): `)).trim() || 'MyChannel';

  header('Step 2 of 5 — Core API Keys');

  info('YouTube Data API v3 Key');
  info('Get it from: console.cloud.google.com → APIs & Services → Enable "YouTube Data API v3" → Credentials → API Key');
  const ytKey = (await ask('YOUTUBE_API_KEY: ')).trim();

  info('\nGemini API Key (free at aistudio.google.com/app/apikey)');
  const geminiKey = (await ask('GEMINI_API_KEY: ')).trim();

  header('Step 3 of 5 — Email Settings');
  info('Gmail address you will SEND from (enable 2FA → App Password first)');
  info('App Password guide: myaccount.google.com/apppasswords');
  const gmailUser = (await ask('GMAIL_USER: ')).trim();
  const gmailPass = (await ask('GMAIL_PASS (16-char app password): ')).trim();
  const recipientEmail = (await ask('RECIPIENT_EMAIL (where to receive reports): ')).trim();

  header('Step 4 of 5 — Optional Integrations');

  info('Notion (leave blank to skip)');
  info('Setup: notion.so/my-integrations → New Integration → copy token');
  const notionKey = (await ask('NOTION_API_KEY (or press Enter to skip): ')).trim();
  let notionDb = '';
  if (notionKey) {
    info('Share a Notion database page with your integration, then copy its ID from the URL');
    notionDb = (await ask('NOTION_DATABASE_ID: ')).trim();
  }

  info('\nDiscord webhook (leave blank to skip)');
  info('Setup: Discord channel → Edit → Integrations → Webhooks → New Webhook → Copy URL');
  const discordUrl = (await ask('DISCORD_WEBHOOK_URL (or press Enter to skip): ')).trim();

  header('Step 5 of 5 — YouTube Auto-Upload (OAuth 2.0)');
  info('This allows the agent to upload videos directly to your YouTube channel.');
  info('1. Go to: console.cloud.google.com → Credentials');
  info('2. Create Credentials → OAuth 2.0 Client ID → Desktop App');
  info('3. Paste Client ID and Client Secret below');
  const oauthClientId     = (await ask('YOUTUBE_OAUTH_CLIENT_ID (or press Enter to skip): ')).trim();
  const oauthClientSecret = oauthClientId ? (await ask('YOUTUBE_OAUTH_CLIENT_SECRET: ')).trim() : '';

  // Build .env content
  const envContent = [
    `# Generated by setup.js on ${new Date().toISOString()}`,
    `CHANNEL_NAME=${channelName}`,
    ``,
    `YOUTUBE_API_KEY=${ytKey}`,
    `GMAIL_USER=${gmailUser}`,
    `GMAIL_PASS=${gmailPass}`,
    `RECIPIENT_EMAIL=${recipientEmail}`,
    `GEMINI_API_KEY=${geminiKey}`,
    ``,
    `# Optional`,
    `NOTION_API_KEY=${notionKey}`,
    `NOTION_DATABASE_ID=${notionDb}`,
    `DISCORD_WEBHOOK_URL=${discordUrl}`,
    ``,
    `# YouTube OAuth (auto-upload)`,
    `YOUTUBE_OAUTH_CLIENT_ID=${oauthClientId}`,
    `YOUTUBE_OAUTH_CLIENT_SECRET=${oauthClientSecret}`,
    `YOUTUBE_OAUTH_REFRESH_TOKEN=`,
  ].join('\n');

  fs.writeFileSync(ENV_PATH, envContent, 'utf8');
  ok('.env file created!');

  // Get refresh token if OAuth was provided
  if (oauthClientId && oauthClientSecret) {
    print('\n');
    info('Now running the YouTube OAuth authorization...');
    info('A URL will appear — open it in your browser, log in with your YouTube channel account, then paste the code back here.\n');
    try {
      execSync('node scripts/auth_youtube.js', { cwd: ROOT, stdio: 'inherit' });
    } catch(e) {
      warn('OAuth setup did not complete. Run `node scripts/auth_youtube.js` manually later.');
    }
  }

  await validate();
  rl.close();
}

async function validate() {
  header('Validating Configuration');
  require('dotenv').config({ path: ENV_PATH });

  const checks = [
    ['CHANNEL_NAME', process.env.CHANNEL_NAME, false],
    ['YOUTUBE_API_KEY', process.env.YOUTUBE_API_KEY, true],
    ['GEMINI_API_KEY', process.env.GEMINI_API_KEY, true],
    ['GMAIL_USER', process.env.GMAIL_USER, true],
    ['GMAIL_PASS', process.env.GMAIL_PASS, true],
    ['RECIPIENT_EMAIL', process.env.RECIPIENT_EMAIL, true],
    ['NOTION_API_KEY', process.env.NOTION_API_KEY, false],
    ['DISCORD_WEBHOOK_URL', process.env.DISCORD_WEBHOOK_URL, false],
    ['YOUTUBE_OAUTH_CLIENT_ID', process.env.YOUTUBE_OAUTH_CLIENT_ID, false],
    ['YOUTUBE_OAUTH_REFRESH_TOKEN', process.env.YOUTUBE_OAUTH_REFRESH_TOKEN, false],
  ];

  let allRequired = true;
  for (const [name, val, required] of checks) {
    if (val) {
      ok(`${name}`);
    } else if (required) {
      err(`${name} is REQUIRED but not set`);
      allRequired = false;
    } else {
      warn(`${name} — not set (optional, pipeline will skip this feature)`);
    }
  }

  print('');
  if (allRequired) {
    ok('All required keys are set! Your agent is ready to run.');
    print(`\n${C.bold}${C.green}Run it now:${C.reset}  node index.js\n`);
    print(`${C.bold}${C.cyan}GitHub Actions${C.reset}: Push to GitHub and add the same keys as repository secrets.\n`);
  } else {
    err('Some required keys are missing. Edit your .env file and re-run: node scripts/setup.js');
  }
}

main().catch((e) => {
  err(e.message);
  rl.close();
  process.exit(1);
});
