'use strict';

/**
 * scripts/setup.js — YouTube AI Agent Interactive Setup
 * ======================================================
 * Run once to configure the agent for a new channel:
 *   node scripts/setup.js
 *
 * This wizard will:
 *   1. Collect all required credentials interactively
 *   2. Write a ready-to-use .env file
 *   3. Validate API keys before saving
 *   4. Guide you through every step with explanations
 */

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');
const https    = require('https');

const ENV_PATH = path.join(__dirname, '..', '.env');

// ── Helpers ───────────────────────────────────────────────────────────────────
const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question, defaultVal = '') {
  return new Promise((resolve) => {
    const hint = defaultVal ? ` (default: ${defaultVal})` : '';
    rl.question(`\n  ${question}${hint}\n  → `, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

function askOptional(question) {
  return new Promise((resolve) => {
    rl.question(`\n  ${question} (press Enter to skip)\n  → `, (answer) => {
      resolve(answer.trim());
    });
  });
}

function print(msg) { process.stdout.write(msg + '\n'); }
function header(title) {
  print('\n' + '═'.repeat(56));
  print(`  ${title}`);
  print('═'.repeat(56));
}
function step(n, title) {
  print(`\n${'─'.repeat(56)}`);
  print(`  STEP ${n}: ${title}`);
  print('─'.repeat(56));
}
function tip(msg) { print(`  💡 ${msg}`); }
function ok(msg)  { print(`  ✅ ${msg}`); }
function warn(msg){ print(`  ⚠️  ${msg}`); }
function url(u)   { print(`  🔗 ${u}`); }

// ── Validators ────────────────────────────────────────────────────────────────
async function validateYouTubeKey(key) {
  return new Promise((resolve) => {
    if (!key || key.length < 10) return resolve(false);
    const testUrl = `https://www.googleapis.com/youtube/v3/videos?part=id&id=dQw4w9WgXcQ&key=${key}`;
    https.get(testUrl, (res) => {
      resolve(res.statusCode === 200);
    }).on('error', () => resolve(false));
  });
}

async function validateGeminiKey(key) {
  return new Promise((resolve) => {
    if (!key || key.length < 10) return resolve(false);
    const options = {
      hostname: 'generativelanguage.googleapis.com',
      path: `/v1beta/models?key=${key}`,
      method: 'GET',
    };
    https.get(options, (res) => {
      resolve(res.statusCode === 200);
    }).on('error', () => resolve(false));
  });
}

// ── Write .env ────────────────────────────────────────────────────────────────
function writeEnv(config) {
  const lines = [
    `# YouTube AI Agent — Generated by setup.js on ${new Date().toISOString().split('T')[0]}`,
    `# Channel: ${config.channelName}`,
    '',
    '# ── Core APIs ──────────────────────────────────────────────────────────────',
    `YOUTUBE_API_KEY=${config.youtubeKey}`,
    `GEMINI_API_KEY=${config.geminiKey}`,
    '',
    '# ── Email Delivery ─────────────────────────────────────────────────────────',
    `GMAIL_USER=${config.gmailUser}`,
    `GMAIL_PASS=${config.gmailPass}`,
    `RECIPIENT_EMAIL=${config.recipientEmail}`,
    '',
    '# ── Channel Branding ────────────────────────────────────────────────────────',
    `CHANNEL_NAME=${config.channelName}`,
    '',
    '# ── Notion Content Calendar (optional — leave blank to skip) ────────────────',
    `NOTION_API_KEY=${config.notionKey || ''}`,
    `NOTION_DATABASE_ID=${config.notionDbId || ''}`,
    '',
    '# ── Discord Notifications (optional — leave blank to skip) ──────────────────',
    `DISCORD_WEBHOOK_URL=${config.discordWebhook || ''}`,
    '',
    '# ── YouTube Auto-Upload OAuth 2.0 ───────────────────────────────────────────',
    '# Run: node scripts/auth_youtube.js  ← to get YOUTUBE_OAUTH_REFRESH_TOKEN',
    `YOUTUBE_OAUTH_CLIENT_ID=${config.oauthClientId || ''}`,
    `YOUTUBE_OAUTH_CLIENT_SECRET=${config.oauthClientSecret || ''}`,
    `YOUTUBE_OAUTH_REFRESH_TOKEN=${config.oauthRefreshToken || ''}`,
    '',
  ];
  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8');
}

// ── Main wizard ───────────────────────────────────────────────────────────────
async function main() {
  header('YouTube AI Agent — Channel Setup Wizard');
  print('\n  This wizard configures the agent for your YouTube channel.');
  print('  It will create a .env file with all required credentials.\n');

  if (fs.existsSync(ENV_PATH)) {
    warn('.env file already exists! Running this will OVERWRITE it.');
    const confirm = await ask('Type YES to overwrite, or press Enter to cancel', '');
    if (confirm.toUpperCase() !== 'YES') {
      print('\n  Cancelled. Your existing .env is unchanged.\n');
      rl.close(); return;
    }
  }

  const config = {};

  // ── STEP 1: Channel Info ──────────────────────────────────────────────────
  step(1, 'Channel Information');
  tip('This is your YouTube channel brand name (shown on thumbnails & scripts)');
  config.channelName = await ask('Your channel/brand name (e.g. NGL, TechBhai, AIwithRaj)');
  if (!config.channelName) { warn('Channel name is required.'); rl.close(); return; }

  // ── STEP 2: YouTube API Key ───────────────────────────────────────────────
  step(2, 'YouTube Data API v3 Key');
  tip('Get a FREE key from Google Cloud Console');
  url('https://console.cloud.google.com/apis/library/youtube.googleapis.com');
  tip('Enable "YouTube Data API v3" → Credentials → Create API Key');
  config.youtubeKey = await ask('Paste your YouTube API key (starts with AIza...)');

  process.stdout.write('  🔍 Validating YouTube API key...');
  const ytValid = await validateYouTubeKey(config.youtubeKey);
  if (ytValid) { ok('YouTube API key is valid!'); }
  else { warn('Could not validate key (might still work if quota is exceeded). Continuing...'); }

  // ── STEP 3: Gemini API Key ────────────────────────────────────────────────
  step(3, 'Google Gemini API Key (Free tier available)');
  url('https://aistudio.google.com/app/apikey');
  tip('Click "Create API Key" → copy the key');
  config.geminiKey = await ask('Paste your Gemini API key (starts with AIza...)');

  process.stdout.write('  🔍 Validating Gemini API key...');
  const geminiValid = await validateGeminiKey(config.geminiKey);
  if (geminiValid) { ok('Gemini API key is valid!'); }
  else { warn('Could not validate key. Continuing...'); }

  // ── STEP 4: Gmail Setup ───────────────────────────────────────────────────
  step(4, 'Gmail Email Delivery');
  tip('Use a Gmail account to send the daily digest email to yourself');
  tip('You need a Gmail App Password (NOT your regular Gmail password)');
  url('https://myaccount.google.com/apppasswords');
  tip('Go to the URL above → Create → App name: "YouTube AI Agent" → Copy the 16-char password');
  config.gmailUser      = await ask('Your Gmail address (e.g. yourname@gmail.com)');
  config.gmailPass      = await ask('Gmail App Password (16 chars, no spaces, e.g. abcd efgh ijkl mnop)');
  config.recipientEmail = await ask('Where to send the daily digest (can be same as Gmail)', config.gmailUser);

  // ── STEP 5: Notion (optional) ─────────────────────────────────────────────
  step(5, 'Notion Content Calendar (OPTIONAL — press Enter to skip)');
  tip('Creates a page in your Notion database for each day\'s content brief');
  url('https://www.notion.so/profile/integrations → New integration → Internal');
  const setupNotion = await ask('Set up Notion? (yes/no)', 'no');
  if (setupNotion.toLowerCase().startsWith('y')) {
    config.notionKey  = await ask('Notion Integration Token (starts with ntn_ or secret_)');
    config.notionDbId = await ask('Notion Database ID (32 chars from database page URL)');
    tip('Also connect your integration to the database: open the DB page → ··· → Connections → add your integration');
  }

  // ── STEP 6: Discord (optional) ────────────────────────────────────────────
  step(6, 'Discord Notifications (OPTIONAL — press Enter to skip)');
  tip('Sends a rich embed to your Discord channel when the pipeline runs');
  tip('Discord → your server → channel settings → Integrations → Webhooks → New Webhook → Copy URL');
  const setupDiscord = await ask('Set up Discord? (yes/no)', 'no');
  if (setupDiscord.toLowerCase().startsWith('y')) {
    config.discordWebhook = await ask('Discord Webhook URL (starts with https://discord.com/api/webhooks/)');
  }

  // ── STEP 7: YouTube OAuth (optional) ─────────────────────────────────────
  step(7, 'YouTube Auto-Upload OAuth 2.0 (OPTIONAL — press Enter to skip)');
  tip('Allows the agent to automatically upload the daily video to your channel');
  tip('Requires a one-time browser authorization after this setup');
  const setupOAuth = await ask('Set up YouTube auto-upload? (yes/no)', 'no');
  if (setupOAuth.toLowerCase().startsWith('y')) {
    print('\n  To get these credentials:');
    url('https://console.cloud.google.com/apis/credentials');
    tip('Create Credentials → OAuth client ID → Desktop app → Download');
    config.oauthClientId     = await ask('OAuth Client ID (ends with .apps.googleusercontent.com)');
    config.oauthClientSecret = await ask('OAuth Client Secret (starts with GOCSPX-)');
    print('\n  ✳️  After setup, run: node scripts/auth_youtube.js');
    print('  This opens a browser link — log in with your YouTube channel\'s Google account');
    print('  Paste the code back and copy the REFRESH TOKEN into .env manually\n');
  }

  // ── Write .env ────────────────────────────────────────────────────────────
  writeEnv(config);

  header('✅ Setup Complete!');
  print('\n  Your .env file has been created successfully.\n');
  print('  📋 What to do next:\n');
  print('  1. If you skipped YouTube OAuth:');
  print('     → Run: node index.js  (to test the pipeline)');
  print('');
  print('  2. If you set up YouTube OAuth:');
  print('     → Run: node scripts/auth_youtube.js');
  print('     → Open the URL, log in, paste the code, copy the refresh token');
  print('     → Add YOUTUBE_OAUTH_REFRESH_TOKEN to .env');
  print('     → Run: node index.js');
  print('');
  print('  3. For automated daily runs (GitHub Actions):');
  print('     → Fork the repo on GitHub');
  print('     → Add all .env values as GitHub Secrets (Settings → Secrets → Actions)');
  print('     → The workflow runs daily at 6:00 AM IST automatically');
  print('');
  print('  📖 Full guide: README.md\n');

  rl.close();
}

main().catch((err) => {
  print(`\n  ❌ Setup error: ${err.message}\n`);
  rl.close();
  process.exit(1);
});
